### PR TITLE
Add build.yaml

### PR DESCRIPTION
**Pull request by oddstr13**
Our current build infrastructure depends on this file.

### CODE REVIEW

**Comment by dkanada** [comment]
I actually removed this because it won't be added to the official repository, since I scrape Vimeo for results.

**Comment by oddstr13** [comment]
Fair enough.
Personally I'd still keep it tho, as it makes building and testing quite easy by just pushing to a local repository.

**Comment by dkanada** [comment]
Ah I see, just added the original file I used to generate my manifest so the information is the same, is that okay?

**Comment by oddstr13** [comment]
Yea, no worries – I just wanted to lazily build the addon with `jprm` :P

**Pull request closed without merging**
